spring:
  profiles:
    group:
      "local" : "local, jwt, oauth, s3"
    active : local
---
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydatabase
    username: root
    password: 1234

  jpa:
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: false
        show_sql: false
    hibernate:
      ddl-auto: update